[package]
name = "espsegs"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
readme = "README.md"
repository = "https://github.com/bjoernQ/espsegs"

[dependencies]
object = "0.31.1"
clap = { version = "4.3.0", features = ["derive"] }
